controllerManager:

  image:
    repository: ghcr.io/azure/eraser-manager
    pullPolicy: IfNotPresent
    # Overrides the image tag whose default is the chart appVersion.
    tag: ""
  additionalArgs: []

  securityContext:
    allowPrivilegeEscalation: false

  resources:
    limits:
      cpu: 100m
      memory: 30Mi
    requests:
      cpu: 100m
      memory: 20Mi

  nodeSelector:
    kubernetes.io/os: linux

  tolerations: []

  affinity: {}

eraser:
  image:
    repository: ghcr.io/azure/eraser
    tag: ""
    args: []

collector:
  image:
    repository: ghcr.io/azure/collector
    tag: ""
    args: []

scanner:
  image:
    repository: ghcr.io/azure/eraser-trivy-scanner
    tag: ""
    args: []

nameOverride: ""
