run:
  timeout: 5m

linters-settings:
  gocritic:
    enabled-tags:
    - performance
  gosec:
    excludes:
    - G108
  lll:
    line-length: 200

  misspell:
    locale: US
  staticcheck:
    go: "1.21"

linters:
  disable-all: true
  enable:
    - errcheck
    - exportloopref
    - forcetypeassert
    - gocritic
    - goconst
    - godot
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive # replacement for golint
    - staticcheck
    - typecheck
    - unused
    - whitespace
