version: "2"

run:
  go: "1.23"

linters:
  default: none
  enable:
    - errcheck
    - copyloopvar # replacement for exportloopref
    - forcetypeassert
    - gocritic
    - goconst
    - godot
    - gosec
    - govet
    - ineffassign
    - misspell
    # - revive # replacement for golint
    - staticcheck # includes gosimple and staticcheck
    - unused
    - whitespace
  settings:
    gocritic:
      enabled-tags:
      - performance
    gosec:
      excludes:
      - G108
    lll:
      line-length: 200
    misspell:
      locale: US
  exclusions:
    paths:
      - "docs/build/assets/files/.*\\.go"

formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
