- op: add
  path: /spec/template/spec/containers/0/volumeMounts
  value: []
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value: { "name": "manager-config", "mountPath": "/controller_manager_config.yaml", "subPath": "controller_manager_config.yaml" }
- op: add
  path: /spec/template/spec/volumes
  value: []
- op: add
  path: /spec/template/spec/volumes/-
  value: { "name": "manager-config", "configMap": { "name": "manager-config" } }
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: "--config=controller_manager_config.yaml"
