- op: add
  path: /spec/template/spec/containers/0/volumeMounts
  value: []
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value: { "name": "config-data", "mountPath": "/eraser_config" }
- op: add
  path: /spec/template/spec/containers/0/volumeMounts/-
  value: { "name": "manager-config", "mountPath": "/eraser_config/config" }
- op: add
  path: /spec/template/spec/volumes
  value: []
- op: add
  path: /spec/template/spec/volumes/-
  value: { "name": "manager-config", "configMap": { "name": "manager-config" } }
- op: add
  path: /spec/template/spec/volumes/-
  value: { "name": "config-data", "emptyDir": { } }
- op: add
  path: /spec/template/spec/containers/0/args/-
  value: "--config=/eraser_config/config/controller_manager_config.yaml"
