apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ template "eraser.name" . }}'
    helm.sh/chart: '{{ template "eraser.name" . }}'
  name: eraser-imagejob-pods-cluster-role
rules:
- apiGroups:
  - eraser.sh
  resources:
  - imagecollectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eraser.sh
  resources:
  - imagecollectors/finalizers
  verbs:
  - update
- apiGroups:
  - eraser.sh
  resources:
  - imagecollectors/status
  verbs:
  - get
  - patch
  - update
