/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/Azure/eraser/api/eraser.sh/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeImageCollectors implements ImageCollectorInterface
type FakeImageCollectors struct {
	Fake *FakeEraserV1alpha1
	ns   string
}

var imagecollectorsResource = schema.GroupVersionResource{Group: "eraser.sh", Version: "v1alpha1", Resource: "imagecollectors"}

var imagecollectorsKind = schema.GroupVersionKind{Group: "eraser.sh", Version: "v1alpha1", Kind: "ImageCollector"}

// Get takes name of the imageCollector, and returns the corresponding imageCollector object, and an error if there is any.
func (c *FakeImageCollectors) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ImageCollector, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(imagecollectorsResource, c.ns, name), &v1alpha1.ImageCollector{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ImageCollector), err
}

// List takes label and field selectors, and returns the list of ImageCollectors that match those selectors.
func (c *FakeImageCollectors) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ImageCollectorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(imagecollectorsResource, imagecollectorsKind, c.ns, opts), &v1alpha1.ImageCollectorList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ImageCollectorList{ListMeta: obj.(*v1alpha1.ImageCollectorList).ListMeta}
	for _, item := range obj.(*v1alpha1.ImageCollectorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested imageCollectors.
func (c *FakeImageCollectors) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(imagecollectorsResource, c.ns, opts))

}

// Create takes the representation of a imageCollector and creates it.  Returns the server's representation of the imageCollector, and an error, if there is any.
func (c *FakeImageCollectors) Create(ctx context.Context, imageCollector *v1alpha1.ImageCollector, opts v1.CreateOptions) (result *v1alpha1.ImageCollector, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(imagecollectorsResource, c.ns, imageCollector), &v1alpha1.ImageCollector{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ImageCollector), err
}

// Update takes the representation of a imageCollector and updates it. Returns the server's representation of the imageCollector, and an error, if there is any.
func (c *FakeImageCollectors) Update(ctx context.Context, imageCollector *v1alpha1.ImageCollector, opts v1.UpdateOptions) (result *v1alpha1.ImageCollector, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(imagecollectorsResource, c.ns, imageCollector), &v1alpha1.ImageCollector{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ImageCollector), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeImageCollectors) UpdateStatus(ctx context.Context, imageCollector *v1alpha1.ImageCollector, opts v1.UpdateOptions) (*v1alpha1.ImageCollector, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(imagecollectorsResource, "status", c.ns, imageCollector), &v1alpha1.ImageCollector{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ImageCollector), err
}

// Delete takes name of the imageCollector and deletes it. Returns an error if one occurs.
func (c *FakeImageCollectors) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(imagecollectorsResource, c.ns, name), &v1alpha1.ImageCollector{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeImageCollectors) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(imagecollectorsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ImageCollectorList{})
	return err
}

// Patch applies the patch and returns the patched imageCollector.
func (c *FakeImageCollectors) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ImageCollector, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(imagecollectorsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ImageCollector{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ImageCollector), err
}
