/*
Copyright 2021.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/Azure/eraser/api/eraser.sh/v1alpha1"
	scheme "github.com/Azure/eraser/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ImageCollectorsGetter has a method to return a ImageCollectorInterface.
// A group's client should implement this interface.
type ImageCollectorsGetter interface {
	ImageCollectors(namespace string) ImageCollectorInterface
}

// ImageCollectorInterface has methods to work with ImageCollector resources.
type ImageCollectorInterface interface {
	Create(ctx context.Context, imageCollector *v1alpha1.ImageCollector, opts v1.CreateOptions) (*v1alpha1.ImageCollector, error)
	Update(ctx context.Context, imageCollector *v1alpha1.ImageCollector, opts v1.UpdateOptions) (*v1alpha1.ImageCollector, error)
	UpdateStatus(ctx context.Context, imageCollector *v1alpha1.ImageCollector, opts v1.UpdateOptions) (*v1alpha1.ImageCollector, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ImageCollector, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ImageCollectorList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ImageCollector, err error)
	ImageCollectorExpansion
}

// imageCollectors implements ImageCollectorInterface
type imageCollectors struct {
	client rest.Interface
	ns     string
}

// newImageCollectors returns a ImageCollectors
func newImageCollectors(c *EraserV1alpha1Client, namespace string) *imageCollectors {
	return &imageCollectors{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the imageCollector, and returns the corresponding imageCollector object, and an error if there is any.
func (c *imageCollectors) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ImageCollector, err error) {
	result = &v1alpha1.ImageCollector{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("imagecollectors").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ImageCollectors that match those selectors.
func (c *imageCollectors) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ImageCollectorList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ImageCollectorList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("imagecollectors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested imageCollectors.
func (c *imageCollectors) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("imagecollectors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a imageCollector and creates it.  Returns the server's representation of the imageCollector, and an error, if there is any.
func (c *imageCollectors) Create(ctx context.Context, imageCollector *v1alpha1.ImageCollector, opts v1.CreateOptions) (result *v1alpha1.ImageCollector, err error) {
	result = &v1alpha1.ImageCollector{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("imagecollectors").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(imageCollector).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a imageCollector and updates it. Returns the server's representation of the imageCollector, and an error, if there is any.
func (c *imageCollectors) Update(ctx context.Context, imageCollector *v1alpha1.ImageCollector, opts v1.UpdateOptions) (result *v1alpha1.ImageCollector, err error) {
	result = &v1alpha1.ImageCollector{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("imagecollectors").
		Name(imageCollector.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(imageCollector).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *imageCollectors) UpdateStatus(ctx context.Context, imageCollector *v1alpha1.ImageCollector, opts v1.UpdateOptions) (result *v1alpha1.ImageCollector, err error) {
	result = &v1alpha1.ImageCollector{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("imagecollectors").
		Name(imageCollector.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(imageCollector).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the imageCollector and deletes it. Returns an error if one occurs.
func (c *imageCollectors) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("imagecollectors").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *imageCollectors) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("imagecollectors").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched imageCollector.
func (c *imageCollectors) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ImageCollector, err error) {
	result = &v1alpha1.ImageCollector{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("imagecollectors").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
