apiVersion: v1
data:
  controller_manager_config.yaml: |
    {{- toYaml .Values.controllerManager.config | nindent 4 }}
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: '{{ .Release.Name }}'
    app.kubernetes.io/managed-by: '{{ .Release.Service }}'
    app.kubernetes.io/name: '{{ template "eraser.name" . }}'
    helm.sh/chart: '{{ template "eraser.name" . }}'
  name: eraser-manager-config
  namespace: '{{ .Release.Namespace }}'
